export default {
  GET_OMDB_SUCCESS: 'GET_OMDB_SUCCESS',
  GET_OMDB_CODE_SUCCESS: 'GET_OMDB_CODE_SUCCESS',
  GET_OMDB_REQUEST: 'GET_OMDB_REQUEST',
  GET_OMDB_CODE_REQUEST: 'GET_OMDB_CODE_REQUEST',
  ADD_FAVE: 'ADD_FAVE',
  REMOVE_FAVE: 'REMOVE_FAVE',
};
